"""updated enrollment table

Revision ID: 02354855b17d
Revises: 2748526ffc43
Create Date: 2025-02-24 17:29:33.398973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02354855b17d'
down_revision: Union[str, None] = '2748526ffc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Enrollments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Enrollments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Enrollments', 'updated_at')
    op.drop_column('Enrollments', 'created_at')
    # ### end Alembic commands ###
