"""modified payments table

Revision ID: 951f92038310
Revises: 213ee512e74b
Create Date: 2025-04-28 16:38:30.230513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '951f92038310'
down_revision: Union[str, None] = '213ee512e74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('indent_id', table_name='Payments')
    op.drop_index('transaction_id', table_name='Payments')
    op.drop_table('Payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('indent_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('payment_status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('session_status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_archived', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], name='Payments_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='Payments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('transaction_id', 'Payments', ['transaction_id'], unique=True)
    op.create_index('indent_id', 'Payments', ['indent_id'], unique=True)
    # ### end Alembic commands ###
