"""added payments table

Revision ID: cc6153f78f50
Revises: 546570f7f74d
Create Date: 2025-04-28 14:56:54.566752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc6153f78f50'
down_revision: Union[str, None] = '546570f7f74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'payment_time')
    op.drop_column('Orders', 'is_verified')
    op.drop_column('Orders', 'payment_method')
    op.drop_column('Orders', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Orders', sa.Column('payment_method', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('Orders', sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('Orders', sa.Column('payment_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
