"""updated course table add column for difficulty

Revision ID: e5d9c3eed6d4
Revises: fb0db8727c81
Create Date: 2025-03-03 15:10:09.158247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d9c3eed6d4'
down_revision: Union[str, None] = 'fb0db8727c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Courses', sa.Column('course_difficulty', sa.Enum('beginner', 'intermediate', 'hard', 'professional', name='difficultyenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Courses', 'course_difficulty')
    # ### end Alembic commands ###
